spring:
  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)  
  datasource:
    url: jdbc:mysql://localhost:3306/wf?useSSL=false
    username: root
    password: 123456
    driver-class: com.mysql.jdbc.Driver
    testWhileIdle: true 
    validationQuery: SELECT 1